In [2]:
import pandas as pd

In [4]:
news = pd.read_csv('news.csv')

In [5]:
news.head()

Headlines  Unnamed: 1  Unnamed: 2
0  Jim Cramer: A better way to invest in the Covi...         NaN         NaN
1     Cramer's lightning round: I would own Teradyne         NaN         NaN
2                                                NaN         NaN         NaN
3  Cramer's week ahead: Big week for earnings, ev...         NaN         NaN
4  IQ Capital CEO Keith Bliss says tech and healt...         NaN         NaN

In [6]:
news['Headlines'][0]

'Jim Cramer: A better way to invest in the Covid-19 vaccine gold rush'

In [7]:
len(news)

3080

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
cv = CountVectorizer(max_df = 0.9,min_df = 2,stop_words = 'english')

In [12]:
news['Headlines'] = news['Headlines'].fillna('')

In [13]:
dtm = cv.fit_transform(news['Headlines'])

In [14]:
dtm

<3080x2066 sparse matrix of type '<class 'numpy.int64'>'
	with 20706 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.decomposition import LatentDirichletAllocation

In [18]:
LDA = LatentDirichletAllocation(n_components = 7,random_state = 42)

In [19]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [21]:
len(cv.get_feature_names_out())

2066

In [22]:
type(cv.get_feature_names_out())

numpy.ndarray

In [25]:
cv.get_feature_names_out()[679]

'fear'

In [26]:
import random

random_word = random.randint(0,784)
cv.get_feature_names_out()[random_word]

'barrick'

In [27]:
len(LDA.components_)

7

In [28]:
type(LDA.components_)

numpy.ndarray

In [29]:
LDA.components_.shape

(7, 2066)

In [30]:
LDA.components_

array([[ 2.54530543,  4.36917172,  0.1452271 , ...,  0.14303692,
         0.14285761,  0.14285808],
       [ 0.14300722,  0.14301149,  4.14223456, ...,  0.14333173,
         0.1428573 ,  0.14484775],
       [ 0.15898105,  0.1429168 ,  0.14313573, ...,  3.0057447 ,
         0.14328638,  1.1428555 ],
       ...,
       [ 0.14288478, 13.95962432,  1.14304444, ...,  2.27821834,
         2.14113873,  0.14285734],
       [ 0.14285742,  2.31558602,  0.14343465, ...,  0.14285774,
         0.14351244,  0.14317536],
       [ 6.94069892,  0.14360999,  0.14329994, ...,  0.14285772,
         0.14285742,  0.14285771]])

In [31]:
single_topic = LDA.components_[0]

In [32]:
single_topic.argsort()

array([1356,  219,  152, ...,  443, 1553,  314])

In [33]:
import numpy as np

In [34]:
arr = np.array([10.200,1])

In [35]:
arr

array([10.2,  1. ])

In [36]:
arr.argsort()

array([1, 0])

In [40]:
single_topic.argsort()[-20:]

array([ 530,  583,  187, 1106, 1193,  945,  270, 1201, 1791, 1288,  587,
       1195,  973,  921,  316,  288,  837,  443, 1553,  314])

In [41]:
top_ten = single_topic.argsort()[-20:]

In [42]:
for index in top_ten:
    print(cv.get_feature_names_out()[index])

digital
ebay
big
market
need
investors
calls
new
tech
paypal
economy
needs
just
industry
cfo
care
health
cramer
says
ceo


In [45]:
for i, topic in enumerate(LDA.components_):
    print(f"The top 20 words for Topic#{i}")
    top_words = [cv.get_feature_names_out()[index] for index in topic.argsort()[-20:][::-1]]  
    print(top_words)  
    print('\n')

The top 20 words for Topic#0
['ceo', 'says', 'cramer', 'health', 'care', 'cfo', 'industry', 'just', 'needs', 'economy', 'paypal', 'tech', 'new', 'calls', 'investors', 'need', 'market', 'big', 'ebay', 'digital']


The top 20 words for Topic#1
['cramer', 'round', 'lightning', 'stock', 'buy', 'don', 'like', 'term', 'stocks', 'long', 'play', 'want', 'good', 'ge', 'think', 'just', 'remix', 'ceo', 'company', 'sell']


The top 20 words for Topic#2
['cramer', 'earnings', 'week', 'fed', 'ahead', 'trump', 'game', 'plan', 'remix', 'china', 'apple', 'ceo', 'new', 'jim', 'season', 'tariffs', 'money', 'rate', 'report', 'mad']


The top 20 words for Topic#3
['cramer', 'ceo', 'says', 'market', 'china', 'trade', 'jim', 'street', 'wall', 'stock', 'rally', 'war', 'coronavirus', 'business', 'stocks', 'explains', 'companies', 'deal', 'big', 'salesforce']


The top 20 words for Topic#4
['cramer', 'jim', 'stocks', 'remix', 'market', 'says', 'stock', 'money', 'buy', 'including', 'mad', 'said', 'investors', 's