In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('movie_review.csv', error_bad_lines=False)

/tmp/ipykernel_229/3312037763.py:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv('movie_review.csv', error_bad_lines=False)


In [13]:
df.head()

Comments   Ratings
0  I didnt go in with big hopes, but i was expect...  positive
1  A unique genre, a well written story (script) ...  positive
2  Majestic at scale, grandeur in VFX, and great ...  positive
3  "Kalki negativepositivepositivepositive" is no...  positive
4  Best Indian movie Nagi combined Hindu mytholog...  positive

In [14]:
df.dropna(inplace = True)

In [17]:
blanks = []

for i, lb, rv in df.itertuples(): 
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [18]:
blanks

[]

In [19]:
df['Ratings'].value_counts()

positive    4600
negative     400
Name: Ratings, dtype: int64

In [21]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/c4aa6a31-8778-4e79-96de-
[nltk_data]     ab90cdd4435a/nltk_data...


True

In [22]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [23]:
sid = SentimentIntensityAnalyzer()

In [25]:
df['scores'] = df['Comments'].apply(lambda review:sid.polarity_scores(review))

In [27]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [29]:
df['comp_score'] = df['compound'].apply(lambda score: 'postive' if score >= 0 else 'negative')

In [30]:
df.head()

Comments   Ratings  \
0  I didnt go in with big hopes, but i was expect...  positive   
1  A unique genre, a well written story (script) ...  positive   
2  Majestic at scale, grandeur in VFX, and great ...  positive   
3  "Kalki negativepositivepositivepositive" is no...  positive   
4  Best Indian movie Nagi combined Hindu mytholog...  positive   

                                              scores  compound comp_score  
0  {'neg': 0.098, 'neu': 0.709, 'pos': 0.193, 'co...    0.9937    postive  
1  {'neg': 0.135, 'neu': 0.723, 'pos': 0.141, 'co...   -0.2960   negative  
2  {'neg': 0.022, 'neu': 0.803, 'pos': 0.176, 'co...    0.9839    postive  
3  {'neg': 0.044, 'neu': 0.773, 'pos': 0.184, 'co...    0.9969    postive  
4  {'neg': 0.089, 'neu': 0.593, 'pos': 0.318, 'co...    0.9831    postive

In [33]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [34]:
accuracy_score(df['Ratings'],df['comp_score'])

0.04

In [35]:
print(classification_report(df['Ratings'],df['comp_score']))

              precision    recall  f1-score   support

    negative       0.50      0.50      0.50       400
    positive       0.00      0.00      0.00      4600
     postive       0.00      0.00      0.00         0

    accuracy                           0.04      5000
   macro avg       0.17      0.17      0.17      5000
weighted avg       0.04      0.04      0.04      5000



/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/envs/anaconda-panel-2023.05-py310/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modi

In [36]:
print(confusion_matrix(df['Ratings'],df['comp_score']))

[[ 200    0  200]
 [ 200    0 4400]
 [   0    0    0]]
